### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by JzfBzsJr** [kajabitools/Kajabi-Downloader#1]
Hi there,
Your tool is awesome. Thank you!
But when I run it there is a mistake - OSError: [Errno 22] Invalid argument: 'C\\Users\\......

Please can you help me understand how to solve this? Windows 11 
I'll really appreciate you, bro🙏

![IMG_4320](https://github.com/user-attachments/assets/08fd5e5f-1791-47e3-8f48-ac7bc20a79b4)

**Comment by kajabitools** [comment]
Hello, i updated app with bug solved 1.1, try and tell me if this solved the problem

**Comment by kajabitools** [comment]
@JzfBzsJr  is ok ? i can clone ?

**Comment by JzfBzsJr** [comment]
I'll try, please give me a couple hours. It's 6 morning here)

**Comment by JzfBzsJr** [comment]
The process began smoothly, but a new mistake appeared. 
![IMG_4321](https://github.com/user-attachments/assets/7b1f4ad2-839d-4b8b-9439-0894b519ab3b)

**Comment by kajabitools** [comment]
try do download again last version https://github.com/kajabitools/Kajabi-Downloader/releases/download/1.2/MyKajabi.exe
in my side is working, else try to setup language in english on your windows pc

**Comment by JzfBzsJr** [comment]
Thank you! I'll try and come back with feedback. I use English on my PC. 
Do you speak any other languages?)

**Comment by JzfBzsJr** [comment]
> The process began smoothly, but a new mistake appeared. 
> 
> ![IMG_4321](https://github.com/user-attachments/assets/7b1f4ad2-839d-4b8b-9439-0894b519ab3b)
> 
> 

The same mistake, bro. I don't know what to say. 
It's important to me to download this course. I'm ready to pay a couple bucks to you. Please help me to download it. 
If possible let's connect on telegram @Jingl_Plastik
